### PR TITLE
Typescript migration (Components are all done, but needs the package.json and tsconfig setup)

### PR DESCRIPTION
**Pull request by swittk**
As mentioned in https://github.com/glancemoney/react-native-numpad/issues/3

### CODE REVIEW

**Comment by cjroth** [comment]
Thank you for this! I'll take a look later this week when I have some time :)

**Comment by cjroth** [comment]
@swittk I'm trying to run this but I'm getting the error:

```
Failed to compile.
~/react-native-numpad/lib/Input.tsx
Module not found: Can't resolve 'react-native-web/dist/exports/Animated' in '~/react-native-numpad/lib'
```

when I run `yarn web`

and I get a blank white screen when I run `yarn ios`.

Is there someone else I should do to get it working?

**Comment by swittk** [comment]
Hi there.
I'm not sure what the issue with react-native-web is, since all imports are exactly the same as before. Maybe it's just that react-native-web isn't specified in the devDependencies field so it wasn't installed? (It is specified in peerDependencies though)

But as for yarn ios not working, it's been like that from the start. Expo requires the "main" field of the package.json to be set to "node_modules/expo/AppEntry.js" in order to run, but when distributing you must have the package.json's "main" field be set to index.js for the library.

So when I was editing the code I changed the "main" field in package.json to "node_modules/expo/AppEntry.js", edited and tested the code in the Expo client, then changed the main field back to index.js when I was done.

**Comment by cjroth** [comment]
Ok that worked, thank you! I need to figure out how to do distribute this next.

**Comment by apenab** [comment]
Hello!. I want to collaborate but I see that a lot of things depend on this pull request. Any status of this pull request?

**Comment by cjroth** [comment]
@apenab I'm going to try to find some time to get this merged this week but pretty busy. Feel free to branch off of this branch - then we could merge this branch first, then yours. What are you hoping to contribute?

**Pull request merged**
